//
// Created by Pablo Brenes on 15 may 2018.
//

#ifndef COMPILADOR_FAMILIASTERMINALES_H
#define COMPILADOR_FAMILIASTERMINALES_H

#define IDENTIFICADOR 0
#define LITERAL_ENTERA 1
#define LITERAL_CARACTER 2
#define LITERAL_STRING 3
#define LITERAL_VERDADERO 4
#define LITERAL_FALSO 5
#define LITERAL_CONJUNTO_ABRIR 6
#define LITERAL_CONJUNTO_CERRAR 7
#define LITERAL_REGISTRO_ABRIR 8
#define LITERAL_REGISTRO_CERRAR 9
#define TERMINADOR 10
#define EVAT 11
#define NAKHO 12
#define KASH 13
/*
#define 14
#define 15
#define 16
*/
#define VERAT 17
#define NAKHAAN 18
/*
#define 19
*/
#define SAVE 20
/*
#define 21
*/
#define HA 22
/*
#define 23
#define 24
#define 25
*/
#define YARAT 26
#define SILLE 27
/*
#define 28
*/
#define IRGE 29
/*
#define 30
#define 31
#define 32
#define 33
*/
#define ASSOKH 34
#define THIKH 35
/*
#define 36
#define 37
#define 38
#define 39
#define 40
#define 41
#define 42
#define 43
#define 44
#define 45
#define 46
*/
#define YOROSOR 47
#define LIRIKH 48
#define LAQAT 49
#define AKAT 50
#define YANQOKH 51
#define RISSAT 52
#define MARILAT 53
#define HETHKAT 54
#define KHALASSAR 55
#define NIVEL16_OPERADOR_ASIGNACION_SIMPLE 56
#define NIVEL16_OPERADOR_ASIGNACION_SUMA 57
#define NIVEL16_OPERADOR_ASIGNACION_RESTA 58
#define NIVEL16_OPERADOR_ASIGNACION_MULTIPLICACION 59
#define NIVEL16_OPERADOR_ASIGNACION_MODULO 60
#define NIVEL16_OPERADOR_ASIGNACION_DIVISION 61
#define NIVEL16_OPERADOR_ASIGNACION_UNION 62
#define NIVEL16_OPERADOR_ASIGNACION_INTERSECCION 63
#define NIVEL16_OPERADOR_ASIGNACION_AGREGAR 64
#define NIVEL16_OPERADOR_ASIGNACION_BORRAR 65
#define NIVEL16_OPERADOR_ASIGNACION_VACIO 66
#define NIVEL16_OPERADOR_ASIGNACION_CONCATENAR 67
#define NIVEL4_OPERADOR_SUMA 68
#define NIVEL4_OPERADOR_RESTA 69
#define NIVEL3_OPERADOR_MULTIPLICACION 70
#define NIVEL3_OPERADOR_DIVISION 71
#define NIVEL3_OPERADOR_MODULO 72
#define NIVEL2_OPERADOR_DECREMENTAR 73
#define NIVEL2_OPERADOR_INCREMENTAR 74
#define NIVEL2_OPERADOR_MAYUSCULEAR 75
#define NIVEL2_OPERADOR_ESLETRA 76
#define NIVEL2_OPERADOR_ESNUMERO 77
#define NIVEL2_OPERADOR_MINUSCULEAR 78
#define NIVEL13_OPERADOR_OR 79
#define NIVEL12_OPERADOR_XOR 80
#define NIVEL11_OPERADOR_AND 81
#define NIVEL2_OPERADOR_NEGACION 82
/*
#define 83
#define 84
#define 85
#define 86
#define 87
#define 88
*/
#define NIVEL5_OPERADOR_CONCATENAR 89
#define NIVEL7_OPERADOR_UNION 90
#define NIVEL7_OPERADOR_INTERSECCION 91
#define NIVEL6_OPERADOR_AGREGAR_CONJUNTO 92
#define NIVEL6_OPERADOR_BORRAR_CONJUNTO 93
#define NIVEL8_OPERADOR_BUSCAR_CONJUNTO 94
#define NIVEL2_OPERADOR_CONJUNTOVACIO 95
#define NIVEL10_OPERADOR_IGUALDAD 96
#define NIVEL10_OPERADOR_DIFERENTE 97
#define NIVEL9_OPERADOR_MENOR 98
#define NIVEL9_OPERADOR_MAYOR 99
#define NIVEL9_OPERADOR_MENOR_IGUAL 100
#define NIVEL9_OPERADOR_MAYOR_IGUAL 101
#define NIVEL4_OPERADOR_FENAT 102
#define NIVEL4_OPERADOR_EJERVALAT 103
#define NIVEL3_OPERADOR_GOVAT 104
#define NIVEL3_OPERADOR_ANAQUISAN 105
#define NIVEL2_OPERADOR_DISISSE 106
#define NIVEL2_OPERADOR_ATHZHOKWAZAR 107
#define NIVEL1_OPERADOR_ACCESO_REGISTRO 108
#define NIVEL1_OPERADOR_ACCESO_STRING 109
/*
#define 110
*/
#define PARENTESIS_IZQUIERDO 111
#define PARENTESIS_DERECHO 112
/*
#define 113
*/
#define CORCHETE_IZQUIERDO 114
#define CORCHETE_DERECHO 115
#define COMA 116
#define LITERAL_FRACCION 117
#endif //COMPILADOR_FAMILIASTERMINALES_H
